"""Shared visual style for Manim scenes — modern dark theme."""

BG_COLOR = "#0d1117"
BG_ACCENT = "#161b22"

PRIMARY = "#4fc3f7"
ACCENT = "#ffb74d"
DIM = "#9e9e9e"
TEXT_COLOR = "#e6edf3"

SUCCESS_COLOR = "#66bb6a"
ERROR_COLOR = "#ef5350"
WARNING_COLOR = "#ffa726"

FORMULA_COLOR = PRIMARY
HIGHLIGHT_COLOR = ACCENT
PREV_STEP_COLOR = DIM

FORMULA_SCALE = 1.3
FORMULA_SCALE_LARGE = 1.5
FINAL_RESULT_SCALE = 1.3

SECTION_LABEL_SCALE = 0.55

FONT_SIZE_TITLE = 56
FONT_SIZE_HEADING = 44
FONT_SIZE_BODY = 36
FONT_SIZE_SMALL = 28
FONT_SIZE_CAPTION = 22

AXES_X_LENGTH = 10
AXES_Y_LENGTH = 6
