"""lessons

Revision ID: 161990f656a1
Revises: c4d5e6f70819
Create Date: 2026-02-17 16:19:40.676329

"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision = '161990f656a1'
down_revision = 'c4d5e6f70819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This revision was autogenerated with duplicate UNIQUE constraints
    # for composite primary-key tables. Keep it idempotent/safe.
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM pg_indexes
            WHERE schemaname = 'public'
              AND indexname = 'ix_lesson_progress_user_id'
          ) THEN
            DROP INDEX ix_lesson_progress_user_id;
          END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_indexes
            WHERE schemaname = 'public'
              AND indexname = 'ix_lesson_progress_user_id'
          ) THEN
            CREATE INDEX ix_lesson_progress_user_id ON lesson_progress (user_id);
          END IF;
        END $$;
        """
    )
