"""add lessons submissions user_profiles and roles

Revision ID: 8da4973a9470
Revises: 9cc6b283e89c
Create Date: 2026-02-10 15:01:44.045596

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da4973a9470'
down_revision = '9cc6b283e89c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), server_default='ru', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Almaty', nullable=False),
    sa.Column('intro_difficulties', sa.Text(), nullable=True),
    sa.Column('intro_notes', sa.Text(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('theory_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    op.create_table('lesson_problem_map',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'problem_id'),
    sa.UniqueConstraint('lesson_id', 'problem_id', name='uq_lesson_problem')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_numeric', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('submission_choice_map',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('choice_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['problem_choices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', 'choice_id'),
    sa.UniqueConstraint('submission_id', 'choice_id', name='uq_submission_choice')
    )
    # unique constraint uq_problem_tag already created in ac7769b176f5_add_catalog_and_problems
    op.add_column('topics', sa.Column('grade_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_topics_grade_level'), 'topics', ['grade_level'], unique=False)

    # Create enum type for user roles and add column
    # Ensure we recreate the type with lowercase values matching the model
    op.execute("DROP TYPE IF EXISTS user_role")
    user_role_enum = sa.Enum(
        'student',
        'teacher',
        'content_maker',
        'moderator',
        'admin',
        name='user_role',
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role_enum, server_default='student', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE IF EXISTS user_role")
    op.drop_index(op.f('ix_topics_grade_level'), table_name='topics')
    op.drop_column('topics', 'grade_level')
    op.drop_table('submission_choice_map')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('lesson_problem_map')
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
