"""add catalog and problems

Revision ID: ac7769b176f5
Revises: 6297b8f0210d
Create Date: 2026-02-09 14:11:36.317836

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7769b176f5'
down_revision = '6297b8f0210d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_kk', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('parent_topic_id', sa.UUID(), nullable=True),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_kk', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_parent_topic_id'), 'topics', ['parent_topic_id'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'NUMERIC', 'SHORT_TEXT', 'MATCH', name='problem_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='problem_difficulty'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='problem_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Author user id; FK defined in migrations'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_created_by'), 'problems', ['created_by'], unique=False)
    op.create_index(op.f('ix_problems_status'), 'problems', ['status'], unique=False)
    op.create_index(op.f('ix_problems_subject_id'), 'problems', ['subject_id'], unique=False)
    op.create_index(op.f('ix_problems_topic_id'), 'problems', ['topic_id'], unique=False)
    op.create_table('problem_answer_keys',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('numeric_answer', sa.Numeric(), nullable=True),
    sa.Column('text_answer', sa.String(length=255), nullable=True),
    sa.Column('answer_pattern', sa.String(length=255), nullable=True),
    sa.Column('tolerance', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_table('problem_choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('choice_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_choices_problem_id'), 'problem_choices', ['problem_id'], unique=False)
    op.create_table('problem_tag_map',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['problem_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id'),
    sa.UniqueConstraint('problem_id', 'tag_id', name='uq_problem_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_tag_map')
    op.drop_index(op.f('ix_problem_choices_problem_id'), table_name='problem_choices')
    op.drop_table('problem_choices')
    op.drop_table('problem_answer_keys')
    op.drop_index(op.f('ix_problems_topic_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_subject_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_status'), table_name='problems')
    op.drop_index(op.f('ix_problems_created_by'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_parent_topic_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('problem_tags')
    # ### end Alembic commands ###
