name: Build & Deploy

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "anelyakurbanova" --password-stdin

      - name: Select environment
        id: env
        run: |
          if [ "${GITHUB_REF_NAME}" = "dev" ]; then
            echo "TAG=staging" >> $GITHUB_OUTPUT
            echo "REMOTE_DIR=/opt/app-staging" >> $GITHUB_OUTPUT
          else
            echo "TAG=prod" >> $GITHUB_OUTPUT
            echo "REMOTE_DIR=/opt/app-prod" >> $GITHUB_OUTPUT
          fi

      - name: Build backend
        run: docker build -t ghcr.io/anelyakurbanova/diploma-backend:${{ steps.env.outputs.TAG }} ./backend

      - name: Push backend
        run: docker push ghcr.io/anelyakurbanova/diploma-backend:${{ steps.env.outputs.TAG }}

      - name: Build frontend
        run: docker build -t ghcr.io/anelyakurbanova/diploma-frontend:${{ steps.env.outputs.TAG }} ./frontend

      - name: Push frontend
        run: docker push ghcr.io/anelyakurbanova/diploma-frontend:${{ steps.env.outputs.TAG }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          envs: GHCR_TOKEN
          script: |
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "anelyakurbanova" --password-stdin
            cd ${{ steps.env.outputs.REMOTE_DIR }}
            docker compose down
            docker image prune -af
            docker compose pull
            docker compose up -d

